//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientLink.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResUI() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientLink.Resx.ResUI", typeof(ResUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to exit the system? 的本地化字符串。
        /// </summary>
        internal static string ExitSystem {
            get {
                return ResourceManager.GetString("ExitSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 operation failed, please check and retry 的本地化字符串。
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation success 的本地化字符串。
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global hotkey {0} registered failed, reason {1} 的本地化字符串。
        /// </summary>
        internal static string RegisterGlobalHotkeyFailed {
            get {
                return ResourceManager.GetString("RegisterGlobalHotkeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global hotkey {0} registered successfully 的本地化字符串。
        /// </summary>
        internal static string RegisterGlobalHotkeySuccessfully {
            get {
                return ResourceManager.GetString("RegisterGlobalHotkeySuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tips 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
    }
}
